---
- name: Install Apache and php on Amazon Linux
  hosts: all
  become: true

  tasks:
    - name: Install httpd (Apache) and php
      package:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution_version == "2023"
