[web_servers]
web_server_amazon ansible_host=44.201.138.100 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/for_laptop.pem

[db_servers]
db_server_ubuntu ansible_host=3.87.66.69 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/for_laptop.pem

[john]
172.26.178.77 ansible_user=john ansible_ssh_private_key_file=~/.ssh/id_ed25519.pem
