---
- hosts: all
  become: true
  pre_tasks:
   - name: install updates (Amazon Linux)
     tags: always
     dnf:
      update_cache: yes
     when: ansible_distribution_version == "2023"

   - name: install updates (Ubuntu)
     tags: always
     apt:
      upgrade: dist
      update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create izzah user
    tags: always
    user:
      name: izzah
      groups: root

  - name: add ssh key for izzah
    tags: always
    authorized_key:
      user: izzah
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW1MKrhdxYZkXwlWddwGg8aby4Pu3RU7prCNB4Xk06o8wlprGSAlRy20LFrxJlSCf1CRnaabD7gR/kV7aJPps87qqpYuuhwJaZKCh6VtWTHrgzo4aTav08wMvhX7R3S0VCpcLUST2WAInWMNP/kapfU6h/hs7d3gv0e2BxLj4CqcJ4vazW83jtn4/a8Zk703eGoKyUm7hz9h/RlIYd6OIsH/ocxEMFvI09mK2qDTyH1R58Al87on5c6GR0bEVRZRNEEPas51TqzblKRq3c8Xff0UCwGDCr+u252KfzMMDypDioTjeV5cWcmDV7LBbsnR/wPuMXLVQJR/9sAIPH6qz3"

  - name: addsudoers file for izzah
    tags: always
    copy:
      src: sudoer_izzah
      dest: /etc/sudoers.d/izzah
      owner: root
      group: root

- hosts: john
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:
    - name: Install httpd (Apache) and php amazon linux 2023
      tags: apache,apache2,amazon
      package:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution_version == "2023"

    - name: start httpd (Amazon)
      tags: apache,apache2,amazon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution_version == "2023"

    - name: Install apache and php for Ubuntu
      tags: apache,apache2,ubuntu
      dnf:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution_version == "Ubuntu"

    - name: start apache (Ubuntu)
      tags: apache,apache2,ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution_version == "Ubuntu"

    - name: copy default html file for site
      tags: apache, apache2,httpd
      copy:
        src: files/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution_version == "2023"

    - name: change e-mail address for admin
      tags: apache, amazon, httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin wongtzemingfrank@gmail.com
      when: ansible_distribution_version == "2023"
      register: httpd

    - name: restart httpd (Amazon)
      tags: apache, amazon, httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package for Ubuntu
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package for Amazon Linux
    tags: db,mariadb,amazon
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "2023"
